// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

var TableNames = struct {
	Payments          string
	UserLevelAccesses string
	Users             string
	Wallets           string
}{
	Payments:          "payments",
	UserLevelAccesses: "user_level_accesses",
	Users:             "users",
	Wallets:           "wallets",
}
